# Generated by Django 3.2.25 on 2025-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
